version: "3.7"

services:
  backend:
    build: .
    ports:
      - 80:8080
    restart: unless-stopped

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app

volumes:
  postgres-data:
