version: "3.7"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /var/www/html/assets/:/deployments/src/main/resources/META-INF/resources/mediafiles/

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db

volumes:
  postgres-data:
