version: "3.7"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db

volumes:
  postgres-data:
